name: goreleaser

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write


permissions:
  contents: write
jobs:
  call-workflow-passing-data:
    uses: IceWhaleTech/github/.github/workflows/go_release.yml@main
    with:
      project-name: CasaOS
      file-name: casaos